name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@04eca2038305127fb1e6683425b6864cd5612f2d
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        # version of golangci-lint to use in form of v1.2.3
        version: v.1.31.0
        # golangci-lint command line arguments
        args: -c .golangci.yml
        # golangci-lint working directory, default is project root
        #working-directory: # optional
        # the token is used for fetching patch of a pull request to show only new issues
        # github-token: # default is ${{ github.token }}
        # if set to true and the action runs on a pull request - the action outputs only newly found issues
        # only-new-issues:

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .